<<<<<<< HEAD
# https://huggingface.co/docs/accelerate/en/package_reference/accelerator

compute_environment: LOCAL_MACHINE
debug: true
distributed_type: MULTI_GPU  #  The distributed training configuration; NO for a single process
downcast_bf16: 'no'
gpu_ids: 0, 1
=======
compute_environment: LOCAL_MACHINE
debug: false
distributed_type: MULTI_GPU
downcast_bf16: 'no'
gpu_ids: 0,1,2,3
>>>>>>> de6d0a15cca1bee68f1620b26eb2a060dff8b017
machine_rank: 0
main_training_function: main
mixed_precision: fp16
num_machines: 1
<<<<<<< HEAD
num_processes: 1 # The total number of processes used for training.
=======
num_processes: 4
>>>>>>> de6d0a15cca1bee68f1620b26eb2a060dff8b017
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
