# https://huggingface.co/docs/accelerate/en/package_reference/accelerator

compute_environment: LOCAL_MACHINE
debug: true
distributed_type: MULTI_GPU  #  The distributed training configuration; NO for a single process
downcast_bf16: 'no'
gpu_ids: 0, 1
machine_rank: 0
main_training_function: main
mixed_precision: fp16
num_machines: 1
num_processes: 1 # The total number of processes used for training.
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
