wandb_version: 1

learning_rate:
  desc: null
  value: 0.0001
architecture:
  desc: null
  value: Diffusion
dataset:
  desc: null
  value: CIFAR-100
epochs:
  desc: null
  value: 400
_wandb:
  desc: null
  value:
    python_version: 3.9.0
    cli_version: 0.16.0
    framework: huggingface
    huggingface_version: 4.35.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1701988461.825506
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 71
      - 83
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 71
      - 83
      3:
      - 16
      - 23
      4: 3.9.0
      5: 0.16.0
      6: 4.35.2
      8:
      - 5
      13: linux-x86_64
