wandb_version: 1

architecture:
  desc: null
  value: DDPM
learning_rate:
  desc: null
  value: 0.0001
batch_size:
  desc: null
  value: 128
dataset:
  desc: null
  value: cifar
epochs:
  desc: null
  value: 400
method:
  desc: null
  value: retrain
pretrained_model:
  desc: null
  value: /projects/leelab/mingyulu/data_att/results/cifar/pruned/models/pruner=magnitude_pruning_ratio=0.3_threshold=0.05
_wandb:
  desc: null
  value:
    python_version: 3.9.0
    cli_version: 0.16.1
    framework: huggingface
    huggingface_version: 4.35.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1701988752.844677
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 71
      - 83
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 71
      - 83
      3:
      - 16
      - 23
      4: 3.9.0
      5: 0.16.1
      6: 4.35.2
      8:
      - 5
      13: linux-x86_64
